"""Add_ML_fields_to_Package

Revision ID: ae76687a1514
Revises: f68536894cac
Create Date: 2026-02-05 22:10:16.426356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae76687a1514'
down_revision: Union[str, None] = 'f68536894cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('packages', sa.Column('traffic_condition', sa.Float(), nullable=True))
    op.add_column('packages', sa.Column('predicted_eta_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'predicted_eta_seconds')
    op.drop_column('packages', 'traffic_condition')
    op.drop_column('packages', 'distance_km')
    # ### end Alembic commands ###
