"""enable_postgis

Revision ID: b2c2c9c62fe5
Revises: 1d4db18da4df
Create Date: 2026-02-12 15:02:48.162440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b2c2c9c62fe5'
down_revision: Union[str, None] = '1d4db18da4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys') # SKIPPED: System table
    op.add_column('drivers', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.execute("CREATE INDEX IF NOT EXISTS idx_drivers_location ON drivers USING gist (location)")
    op.add_column('location_history', sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.execute("CREATE INDEX IF NOT EXISTS idx_location_history_location ON location_history USING gist (location)")
    op.add_column('packages', sa.Column('destination_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.execute("CREATE INDEX IF NOT EXISTS idx_packages_destination_location ON packages USING gist (destination_location)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_packages_destination_location', table_name='packages', postgresql_using='gist')
    op.drop_column('packages', 'destination_location')
    op.drop_index('idx_location_history_location', table_name='location_history', postgresql_using='gist')
    op.drop_column('location_history', 'location')
    op.drop_index('idx_drivers_location', table_name='drivers', postgresql_using='gist')
    op.drop_column('drivers', 'location')
    # op.create_table('spatial_ref_sys') # SKIPPED
    # ### end Alembic commands ###
