"""Add dispatch and tracking models

Revision ID: e647f96280c3
Revises: ae76687a1514
Create Date: 2026-02-10 11:56:51.041841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e647f96280c3'
down_revision: Union[str, None] = 'ae76687a1514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_availability',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_history_driver_id'), 'location_history', ['driver_id'], unique=False)
    op.create_table('dispatch_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('package_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drivers', sa.Column('vehicle_id', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('shift_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('drivers', sa.Column('shift_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('packages', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('packages', sa.Column('scheduled_window_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('packages', sa.Column('scheduled_window_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'scheduled_window_end')
    op.drop_column('packages', 'scheduled_window_start')
    op.drop_column('packages', 'priority')
    op.drop_column('drivers', 'shift_end')
    op.drop_column('drivers', 'shift_start')
    op.drop_column('drivers', 'vehicle_id')
    op.drop_table('dispatch_jobs')
    op.drop_index(op.f('ix_location_history_driver_id'), table_name='location_history')
    op.drop_table('location_history')
    op.drop_table('driver_availability')
    # ### end Alembic commands ###
